<template>
  <main>
    <page-section>
      <heading variant="block">Privacy Policy</heading>
      <heading level="4">Effective date: June 21, 2018</heading>
      <paragraph>
        Vue.js Limited ("us", "we", or "our") operates the https://vuejs.london website (the
        "Service").
      </paragraph>
      <paragraph>
        This page informs you of our policies regarding the collection, use, and disclosure of
        personal data when you use our Service and the choices you have associated with that data.
      </paragraph>
      <paragraph>
        We use your data to provide and improve the Service. By using the Service, you agree to the
        collection and use of information in accordance with this policy. Unless otherwise defined
        in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our
        Terms and Conditions, accessible from https://vuejs.london
      </paragraph>
      <heading level="2">Definitions</heading>
      <heading level="3">Service</heading>
      <paragraph>Service is the https://vuejs.london website operated by Vue.js Limited</paragraph>
      <heading level="3">Personal Data</heading>
      <paragraph>
        Personal Data means data about a living individual who can be identified from those data (or
        from those and other information either in our possession or likely to come into our
        possession).
      </paragraph>
      <heading level="3">Usage Data</heading>
      <paragraph>
        Usage Data is data collected automatically either generated by the use of the Service or
        from the Service infrastructure itself (for example, the duration of a page visit).
      </paragraph>
      <heading level="3">Cookies</heading>
      <paragraph
        >Cookies are small pieces of data stored on your device (computer or mobile
        device).</paragraph
      >
      <heading level="3">Data Controller</heading>
      <paragraph>
        Data Controller means the natural or legal person who (either alone or jointly or in common
        with other persons) determines the purposes for which and the manner in which any personal
        information are, or are to be, processed.
      </paragraph>
      <paragraph
        >For the purpose of this Privacy Policy, we are a Data Controller of your Personal
        Data.</paragraph
      >
      <heading level="3">Data Processors (or Service Providers)</heading>
      <paragraph>
        Data Processor (or Service Provider) means any natural or legal person who processes the
        data on behalf of the Data Controller.
      </paragraph>
      <paragraph>
        We may use the services of various Service Providers in order to process your data more
        effectively.
      </paragraph>
      <heading level="3">Data Subject (or User)</heading>
      <paragraph>
        Data Subject is any living individual who is using our Service and is the subject of
        Personal Data.
      </paragraph>
      <heading level="2">Information Collection and Use</heading>
      <paragraph>
        We collect several different types of information for various purposes to provide and
        improve our Service to you.
      </paragraph>
      <heading level="2">Types of Data Collected</heading>
      <heading level="2">Personal Data</heading>
      <paragraph>
        While using our Service, we may ask you to provide us with certain personally identifiable
        information that can be used to contact or identify you ("Personal Data"). Personally
        identifiable information may include, but is not limited to:
      </paragraph>
      <list>
        <list-item>Email address</list-item>
        <list-item>First name and last name</list-item>
        <list-item>Cookies and Usage Data</list-item>
      </list>
      <paragraph>
        We may use your Personal Data to contact you with newsletters, marketing or promotional
        materials and other information that may be of interest to you. You may opt out of receiving
        any, or all, of these communications from us by following the unsubscribe link or
        instructions provided in any email we send.
      </paragraph>
      <heading level="2">Usage Data</heading>
      <paragraph>
        We may also collect information how the Service is accessed and used ("Usage Data"). This
        Usage Data may include information such as your computer's Internet Protocol address (e.g.
        IP address), browser type, browser version, the pages of our Service that you visit, the
        time and date of your visit, the time spent on those pages, unique device identifiers and
        other diagnostic data.
      </paragraph>
      <heading level="2">Tracking &amp; Cookies Data</heading>
      <paragraph>
        We use cookies and similar tracking technologies to track the activity on our Service and
        hold certain information.
      </paragraph>
      <paragraph>
        Cookies are files with small amount of data which may include an anonymous unique
        identifier. Cookies are sent to your browser from a website and stored on your device.
        Tracking technologies also used are beacons, tags, and scripts to collect and track
        information and to improve and analyze our Service.
      </paragraph>
      <paragraph>
        You can instruct your browser to refuse all cookies or to indicate when a cookie is being
        sent. However, if you do not accept cookies, you may not be able to use some portions of our
        Service.
      </paragraph>
      <paragraph>Examples of Cookies we use:</paragraph>
      <list>
        <list-item>
          Session Cookies.&nbsp;We use Session Cookies to operate our Service.
        </list-item>
        <list-item>
          Preference Cookies.&nbsp;We use Preference Cookies to remember your preferences and
          various settings.
        </list-item>
        <list-item>
          Security Cookies.&nbsp;We use Security Cookies for security purposes.
        </list-item>
      </list>
      <heading level="2">Use of Data</heading>
      <paragraph>Vue.js Limited uses the collected data for various purposes:</paragraph>
      <list>
        <list-item>
          To provide and maintain our Service
        </list-item>
        <list-item>
          To notify you about changes to our Service
        </list-item>
        <list-item>
          To allow you to participate in interactive features of our Service when you choose to do
          so
        </list-item>
        <list-item>
          To provide customer support
        </list-item>
        <list-item>
          To gather analysis or valuable information so that we can improve our Service
        </list-item>
        <list-item>
          To monitor the usage of our Service
        </list-item>
        <list-item>
          To detect, prevent and address technical issues
        </list-item>
        <list-item>
          To provide you with news, special offers and general information about other goods,
          services and events which we offer that are similar to those that you have already
          purchased or enquired about unless you have opted not to receive such information
        </list-item>
      </list>
      <heading level="2">
        Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)
      </heading>
      <paragraph>
        If you are from the European Economic Area (EEA), Vue.js Limited legal basis for collecting
        and using the personal information described in this Privacy Policy depends on the Personal
        Data we collect and the specific context in which we collect it.
      </paragraph>
      <paragraph>Vue.js Limited may process your Personal Data because:</paragraph>
      <list>
        <list-item>We need to perform a contract with you</list-item>
        <list-item>You have given us permission to do so</list-item>
        <list-item>
          The processing is in our legitimate interests and it's not overridden by your rights
        </list-item>
        <list-item>For payment processing purposes</list-item>
        <list-item>To comply with the law</list-item>
      </list>
      <heading level="2">Retention of Data</heading>
      <paragraph>
        Vue.js Limited will retain your Personal Data only for as long as is necessary for the
        purposes set out in this Privacy Policy. We will retain and use your Personal Data to the
        extent necessary to comply with our legal obligations (for example, if we are required to
        retain your data to comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
      </paragraph>
      <paragraph>
        Vue.js Limited will also retain Usage Data for internal analysis purposes. Usage Data is
        generally retained for a shorter period of time, except when this data is used to strengthen
        the security or to improve the functionality of our Service, or we are legally obligated to
        retain this data for longer time periods.
      </paragraph>
      <heading level="2">Transfer of Data</heading>
      <paragraph>
        Your information, including Personal Data, may be transferred to — and maintained on —
        computers located outside of your state, province, country or other governmental
        jurisdiction where the data protection laws may differ than those from your jurisdiction.
      </paragraph>
      <paragraph>
        If you are located outside United Kingdom and choose to provide information to us, please
        note that we transfer the data, including Personal Data, to United Kingdom and process it
        there.
      </paragraph>
      <paragraph>
        Your consent to this Privacy Policy followed by your submission of such information
        represents your agreement to that transfer.
      </paragraph>
      <paragraph>
        Vue.js Limited will take all steps reasonably necessary to ensure that your data is treated
        securely and in accordance with this Privacy Policy and no transfer of your Personal Data
        will take place to an organization or a country unless there are adequate controls in place
        including the security of your data and other personal information.
      </paragraph>
      <heading level="2">Disclosure of Data</heading>
      <heading level="3">Disclosure for Law Enforcement</heading>
      <paragraph>
        Under certain circumstances, Vue.js Limited may be required to disclose your Personal Data
        if required to do so by law or in response to valid requests by public authorities (e.g. a
        court or a government agency).
      </paragraph>
      <heading level="3">Legal Requirements</heading>
      <paragraph>
        Vue.js Limited may disclose your Personal Data in the good faith belief that such action is
        necessary to:
      </paragraph>
      <list>
        <list-item>To comply with a legal obligation</list-item>
        <list-item>To protect and defend the rights or property of Vue.js Limited</list-item>
        <list-item
          >To prevent or investigate possible wrongdoing in connection with the Service</list-item
        >
        <list-item>To protect the personal safety of users of the Service or the public</list-item>
        <list-item>To protect against legal liability</list-item>
      </list>
      <heading level="2">Security of Data</heading>
      <paragraph>
        The security of your data is important to us, but remember that no method of transmission
        over the Internet, or method of electronic storage is 100% secure. While we strive to use
        commercially acceptable means to protect your Personal Data, we cannot guarantee its
        absolute security.
      </paragraph>
      <heading level="2"
        >Your Data Protection Rights Under General Data Protection Regulation (GDPR)</heading
      >
      <paragraph>
        If you are a resident of the European Economic Area (EEA), you have certain data protection
        rights. Vue.js Limited aims to take reasonable steps to allow you to correct, amend, delete,
        or limit the use of your Personal Data.
      </paragraph>
      <paragraph>
        If you wish to be informed what Personal Data we hold about you and if you want it to be
        removed from our systems, please contact us.
      </paragraph>
      <paragraph
        >In certain circumstances, you have the following data protection rights:</paragraph
      >
      <list>
        <list-item>
          The right to access, update or to delete the information we have on you.&nbsp;Whenever
          made possible, you can access, update or request deletion of your Personal Data directly
          within your account settings section. If you are unable to perform these actions yourself,
          please contact us to assist you.
        </list-item>
        <list-item>
          The right of rectification.&nbsp;You have the right to have your information rectified if
          that information is inaccurate or incomplete.
        </list-item>
        <list-item>
          The right to object.&nbsp;You have the right to object to our processing of your Personal
          Data.
        </list-item>
        <list-item>
          The right of restriction.&nbsp;You have the right to request that we restrict the
          processing of your personal information.
        </list-item>
        <list-item>
          The right to data portability.&nbsp;You have the right to be provided with a copy of the
          information we have on you in a structured, machine-readable and commonly used format.
        </list-item>
        <list-item>
          The right to withdraw consent.&nbsp;You also have the right to withdraw your consent at
          any time where Vue.js Limited relied on your consent to process your personal information.
        </list-item>
      </list>
      <paragraph>
        Please note that we may ask you to verify your identity before responding to such requests.
      </paragraph>
      <paragraph>
        You have the right to complain to a Data Protection Authority about our collection and use
        of your Personal Data. For more information, please contact your local data protection
        authority in the European Economic Area (EEA).
      </paragraph>
      <heading level="2">Service Providers</heading>
      <paragraph>
        We may employ third party companies and individuals to facilitate our Service ("Service
        Providers"), to provide the Service on our behalf, to perform Service-related services or to
        assist us in analyzing how our Service is used.
      </paragraph>
      <paragraph>
        These third parties have access to your Personal Data only to perform these tasks on our
        behalf and are obligated not to disclose or use it for any other purpose.
      </paragraph>
      <heading level="2">Analytics</heading>
      <paragraph
        >We may use third-party Service Providers to monitor and analyze the use of our
        Service.</paragraph
      >
      <paragraph>Google Analytics</paragraph>
      <paragraph>
        Google Analytics is a web analytics service offered by Google that tracks and reports
        website traffic. Google uses the data collected to track and monitor the use of our Service.
        This data is shared with other Google services. Google may use the collected data to
        contextualize and personalize the ads of its own advertising network.
      </paragraph>
      <paragraph>
        You can opt-out of having made your activity on the Service available to Google Analytics by
        installing the Google Analytics opt-out browser add-on. The add-on prevents the Google
        Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google
        Analytics about visits activity.
      </paragraph>
      <paragraph>
        For more information on the privacy practices of Google, please visit the Google Privacy
        &amp; Terms web page:&nbsp;
        <anchor href="https://policies.google.com/privacy?hl=en" rel="noopener" target="_blank"
          >https://policies.google.com/privacy?hl=en</anchor
        >
      </paragraph>
      <heading level="2">Payments</heading>
      <paragraph>
        We may provide paid products and/or services within the Service. In that case, we use
        third-party services for payment processing (e.g. payment processors).
      </paragraph>
      <paragraph>
        We will not store or collect your payment card details. That information is provided
        directly to our third-party payment processors whose use of your personal information is
        governed by their Privacy Policy. These payment processors adhere to the standards set by
        PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands
        like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the
        secure handling of payment information.
      </paragraph>
      <paragraph>The payment processors we work with are:</paragraph>
      <heading level="3">Stripe</heading>
      <paragraph>
        Their Privacy Policy can be viewed at&nbsp;
        <anchor href="https://stripe.com/us/privacy" rel="noopener" target="_blank"
          >https://stripe.com/us/privacy</anchor
        >
      </paragraph>
      <heading level="2">Links to Other Sites</heading>
      <paragraph>
        Our Service may contain links to other sites that are not operated by us. If you click on a
        third party link, you will be directed to that third party's site. We strongly advise you to
        review the Privacy Policy of every site you visit.
      </paragraph>
      <paragraph>
        We have no control over and assume no responsibility for the content, privacy policies or
        practices of any third party sites or services.
      </paragraph>
      <heading level="2">Children's Privacy</heading>
      <paragraph>Our Service does not address anyone under the age of 18 ("Children").</paragraph>
      <paragraph>
        We do not knowingly collect personally identifiable information from anyone under the age of
        18. If you are a parent or guardian and you are aware that your child has provided us with
        Personal Data, please contact us. If we become aware that we have collected Personal Data
        from children without verification of parental consent, we take steps to remove that
        information from our servers.
      </paragraph>
      <heading level="2">Changes to This Privacy Policy</heading>
      <paragraph>
        We may update our Privacy Policy from time to time. We will notify you of any changes by
        posting the new Privacy Policy on this page.
      </paragraph>
      <paragraph>
        We will let you know via email and/or a prominent notice on our Service, prior to the change
        becoming effective and update the "effective date" at the top of this Privacy Policy.
      </paragraph>
      <paragraph>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this
        Privacy Policy are effective when they are posted on this page.
      </paragraph>
      <heading level="2">Contact Us</heading>
      <paragraph>
        If you have any questions about this Privacy Policy, please contact us by email:
        team@vuejs.london
      </paragraph>
    </page-section>
  </main>
</template>

<script>
import Anchor from '~/components/Anchor'
import Heading from '~/components/Heading'
import List from '~/components/List'
import ListItem from '~/components/ListItem'
import PageSection from '~/components/PageSection'
import Paragraph from '~/components/Paragraph'

export default {
  head: {
    title: 'Vue.js London 2019 | Privacy Policy',
  },

  components: {
    Anchor,
    Heading,
    List,
    ListItem,
    PageSection,
    Paragraph,
  },
}
</script>
